### ISSUE TITLE
Validators is not working with nested data

### ISSUE THREAD

**Issue by lukasborawski** [cj/vuelidation#1]
I have this nested data validators, and if this is defined without `userData` object it's working correctly, but within not. 

    vuelidation: {
      data: {
        userData: {
          name: {
            required: true
          },
          email: {
            required: true,
            email: true
          },
          password: {
            required: true
          },
          nickname: {
            required: true
          }
        }
      }

**Comment by cj** [comment]
@lukasborawski Here's an example using nested data https://codepen.io/cj/pen/gWNVOr

**Comment by mgkimsal** [comment]
FWIW, the nesting doesn't work.  It's recognized, but... change "required" to false in the codepen example.  It'll still be required.
