### ISSUE TITLE
Between filter is not working

### ISSUE THREAD

**Issue by lukasborawski** [cj/vuelidation#2]
The best example is the official example: https://codepen.io/anon/pen/GmbBBg 

https://github.com/cj/vuelidation/blob/master/src/validations.js#L35
There supposed to be length?

**Comment by cj** [comment]
@lukasborawski I'll get this fixed and pushed today.  Thank you for finding that!

**Comment by lukasborawski** [comment]
@cj Awesome, can you update NPM also?

**Comment by cj** [comment]
@lukasborawski of course!

**Comment by cj** [comment]
@lukasborawski sorry for the confusion, `between` is working as intended.  It's meant for things like a number slide or age range.  Where a number needs between two other numbers.  I think what you're looking for is something like `betweenLength`.  I'll add that and link it to this ticket.

**Comment by cj** [comment]
@lukasborawski ok, added `betweenLength` https://github.com/cj/vuelidation/commit/035f1c12ade9363acd48c4f8c8c87e72301f6dea and updated npm to `0.0.10`.

**Comment by lukasborawski** [comment]
@cj Super, thank you a lot for quick reaction! Cheers.
