### ISSUE TITLE
The postal code validation

### ISSUE THREAD

**Issue by lukasborawski** [cj/vuelidation#6]
So, @cj I'm trying to set some validation rules for postal-code field:

```
postal: {
  required: true,
  alphaDash: true,
  betweenLength: {
    min: 5,
    max: 6
  }         
},
```

but when I'm typing any postal code with `-` sign there is required error. Always. Also the `betweenLength` filter is not working at all whan i have `-` in my value. And all issues are actual for number input type.

**Comment by cj** [comment]
@lukasborawski If you are trying to validate a normal zip and a zip+4 in a single input, it would have to be a text input as a hyphen is not numeric, the max would also be 10 as you have to include the hyphen.  Here is an example https://codepen.io/cj/pen/gXyeGQ that would work with `75023` and `75023-8320`.  The better option would be to do a custom validation method i.e.

```
      zipCode (value, args) {
        let msg = 'Must be either 55555 or 55555-4444'
        let valid = false
        
        if (value.includes('-') && value.length === 10) {
          valid = true
        } else if (value.length === 5) {
          valid = true
        }

        return [valid, msg]
      },
```

Here is an example using that https://codepen.io/cj/pen/wPZmYV.

I hope this helps!  Let me know if you have any other questions!
