### ISSUE TITLE
Validation not working with objects

### ISSUE THREAD

**Issue by usmanmirza** [cj/vuelidation#7]
Hi @cj, validation is not working with object fields as I'm working on a project in which I have a form to submit which have multiple fields in that I'm using an Object FormData with nested fields like..`<input type="text" v-model="FormData.Name"/>` can we apply validations by using object fields such as `vuelidation: {
      data: {
        FormData: {
            Name:{
              required: true
            }
        },
      },
    },`
Thanks in Advance 😃

**Comment by cj** [comment]
@usmanmirza Check out issue #1, it has an example of using nested data.  I'll add that example to the README.me 😄 

Let me know if you need any other help!
